// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login Page', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".text-left")).click()
    {
      const element = await driver.findElement(By.css(".text-left"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("material-tailwind-select-2")).click()
    await driver.findElement(By.css(".relative:nth-child(3) > .peer")).click()
    await driver.findElement(By.css(".relative:nth-child(3) > .peer")).sendKeys("new@gmail.com")
    await driver.findElement(By.css(".relative:nth-child(5) > .peer")).click()
    await driver.findElement(By.css(".relative:nth-child(5) > .peer")).sendKeys("123456")
    await driver.findElement(By.css(".align-middle")).click()
    await driver.findElement(By.css(".col-span-8 > .w-full")).click()
  })
})
